VERSION 0.8


FROM golang:1.23.3-alpine
WORKDIR /rundoodefs

# setup protoc
RUN apk add --no-cache protobuf protobuf-dev
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

proto-go:
  ENV PATH=$PATH:/root/go/bin
  RUN go mod init proto-go

  COPY ./v1/rundoo.proto /rundoodefs
  RUN mkdir -p /rundoodefs/go-api
  RUN protoc --proto_path=/rundoodefs --go_out=/rundoodefs/go-api --go-grpc_out=/rundoodefs/go-api /rundoodefs/rundoo.proto
  SAVE ARTIFACT ./go-api /rundoo-pb AS LOCAL rundoo-pb

proto-all:
  BUILD +proto-go
