VERSION 0.8


FROM golang:1.23.3-alpine
WORKDIR /rundoo

# setup protoc
RUN apk add --no-cache protobuf protobuf-dev
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

proto-go:
  ENV PATH=$PATH:/root/go/bin
  RUN go mod init proto-go

  RUN mkdir -p /rundoo/app/api/v1
  COPY ./v1/rundoo.proto /rundoo/app/api/v1
  RUN protoc --proto_path=/rundoo/app/api/v1 --go_out=/rundoo/app/api/v1 --go-grpc_out=/rundoo/app/api/v1 /rundoo/app/api/v1/rundoo.proto
  SAVE ARTIFACT ./app/api/v1 /rundoo-pb AS LOCAL rundoo-pb

proto-all:
  BUILD +proto-go
