VERSION 0.8


FROM golang:1.23.3-alpine
WORKDIR /rundoo

# setup protoc
RUN apk add --no-cache protobuf protobuf-dev
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

proto-go:
  ENV PATH=$PATH:/root/go/bin
  RUN go mod init proto-go

  RUN mkdir -p /rundoo/app/api/v1
  COPY ./v1/rundoo.proto /rundoo/app/api/v1
  # COPY ../../ /rundoo/app doesn't seem to work, the same result as the above
  RUN protoc app/api/v1/*.proto \
            --go_out=. \
            --go_opt=paths=source_relative \
            --go-grpc_out=. \
            --go-grpc_opt=paths=source_relative \
            --proto_path=.
  SAVE ARTIFACT ./app/api/v1 AS LOCAL v1

proto-all:
  BUILD +proto-go

