apiVersion: v1
kind: Service
metadata:
  name: logservice
  namespace: rundook
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: logservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logservice
  namespace: rundook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logservice
  template:
    metadata:
      labels:
        app: logservice
    spec:
      containers:
        - name: api
          image: gators/rundoo-log
          envFrom:
            - secretRef:
                name: logservice-connection
