apiVersion: v1
kind: Service
metadata:
  name: logservice
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: logservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logservice 
spec:
  selector:
    matchLabels:
      app: logservice
  template:
    metadata:
      labels:
        app: logservice
    spec:
      containers:
        - name: api
          image: gators/rundoo-log
          