apiVersion: v1
kind: Service
metadata:
  name: logservice
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: logservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logservice 
spec:
  selector:
    matchLabels:
      app: logservice
  template:
    metadata:
      labels:
        app: logservice
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -zv rundoo-db 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: rundoo-log
          image: gators/rundoo-log
          ports:
            - containerPort: 4000
          