apiVersion: v1
kind: Service
metadata:
  name: registryservice
  namespace: rundook
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: registryservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registryservice
  namespace: rundook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registryservice
  template:
    metadata:
      labels:
        app: registryservice
    spec:
      containers:
        - name: api
          image: gators/rundoo-registry
          envFrom:
            - secretRef:
                name: registryservice-connection
