apiVersion: v1
kind: Service
metadata:
  name: registryservice
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: registryservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registryservice
spec:
  selector:
    matchLabels:
      app: registryservice
  template:
    metadata:
      labels:
        app: registryservice
    spec:
      containers:
        - name: api
          image: gators/rundoo-registry
          