apiVersion: v1
kind: Service
metadata:
  name: registryservice
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: registryservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registryservice
spec:
  selector:
    matchLabels:
      app: registryservice
  template:
    metadata:
      labels:
        app: registryservice
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -zv rundoo-db 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: rundoo-registry
          image: gators/rundoo-registry
          ports:
            - containerPort: 3000
          