apiVersion: v1
kind: Service
metadata:
  name: rundoo-api
spec:
  ports:
    - port: 6000
      targetPort: 6000
  selector:
    app: rundoo-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundoo-api
spec:
  selector:
    matchLabels:
      app: rundoo-api
  template:
    metadata:
      labels:
        app: rundoo-api
    spec:
      containers:
        - name: api
          image: gators/rundoo-api
          