apiVersion: v1
kind: Service
metadata:
  name: rundook-db
  namespace: rundook
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: rundook-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundook-db
  namespace: rundook
spec:
  selector:
    matchLabels:
      app: rundook-db
  template:
    metadata:
      labels:
        app: rundook-db
    spec:
      containers:
        - name: db
          image: gators/rundoo-db
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/pg-password
          volumeMounts:
            - name: db-password
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: db-password
          secret:
            secretName: rundook-db-password
