apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundoo-db
spec:
  selector:
    matchLabels:
      app: rundoo-db
  template:
    metadata:
      labels:
        app: rundoo-db
    spec:
      containers:
        - name: rundoo-db-deployment
          image: gators/rundoo-db
          env:
            - name: POSTGRES_PASSWORD
              value: uber
          ports:
            - containerPort: 5432
          
