services:

  rundoo-db:
    image: gators/rundoo-db
    build:
      context: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=uber
    networks:
      - rundoo-net

  rundoo-api:
    image: gators/rundoo-api
    build:
      context: rundoo-api
    ports:
      - "6000:6000"
    networks:
      - rundoo-net
    depends_on:
      - rundoo-db
      - logservice
      - registryservice

  logservice:
    image: gators/rundoo-log
    build:
      context: logservice
    ports:
      - "4000:4000"
    networks:
      - rundoo-net
    depends_on:
      - rundoo-db
      - registryservice
  
  registryservice:
    image: gators/rundoo-registry
    build:
      context: registryservice
    ports:
      - "3000:3000"
    networks:
      - rundoo-net
    depends_on:
      - rundoo-db
  
  portal:
    image: gators/golang-dlv
    build:
      context: portal
    ports:
      - "5050:5050"
    networks:
      - rundoo-net
    depends_on:
      - rundoo-api      
      - registryservice
      - logservice

  tcpdump:
    image: nicolaka/netshoot
    command: ["tcpdump", "-v", "-i", "eth0"]
    networks:
      - rundoo-net
    cap_add:
      - NET_ADMIN

networks:
  rundoo-net: