# syntax = docker+earthly:latest

VERSION 0.8

deps:
    FROM golang:1.23.3-alpine
    WORKDIR /rundoo/app
    COPY . . 
    COPY ./* .
    COPY ./api/+proto-go/* ./api/v1   
    


build-logservice:
    FROM +deps

    # RUN go build -o /out/logservice ./cmd/logservice
    # SAVE ARTIFACT  /out/logservice  /logservice AS LOCAL build/logservice
    RUN go build -o logservice ./cmd/logservice
   

build-api:
    FROM +proto-go
    RUN go build -o /out/api ./api/v1

docker-logservice:
    FROM +build-logservice
    ENTRYPOINT ["./logservice"]
    SAVE IMAGE logservice:latest

all:
    FROM +build-logservice  
    FROM +docker-logservice
    