# syntax = docker+earthly:latest

VERSION 0.8

deps:
    FROM golang:1.23.3 
    WORKDIR /go/src/github.com/gator1/rundoo/app

    COPY app/go.mod app/go.sum ./
    RUN go mod download

    COPY app/ .


build-logservice:
    FROM ../../api+proto-go
    WORKDIR /go/src/github.com/gator1/rundoo/app

    COPY ../../go.mod  ./
    RUN go mod download

    COPY ../.. .
    RUN go build -o /out/logservice ./cmd/logservice
    SAVE ARTIFACT  /out/logservice  /logservice AS LOCAL build/logservice



build-api:
    FROM +proto-go
    RUN go build -o /out/api ./api/v1

docker-logservice:
    COPY +build/go-exlogserviceample .
    ENTRYPOINT ["/rundoo/logservice"]
    SAVE IMAGE logservice:latest

all:
    FROM +build-logservice  
    FROM +docker-logservice
    